# add environment specific frontend variables here
http_port: 80
https_port: 443
proxy_domain: staging.allu.kaupunkiymparisto.fi
proxypass_api_context: /api/
proxypass_api_target: "http://{{ allu_ui_service_name }}:9000/"
proxypass_external_context: /external/
proxypass_external_target: "http://{{ external_service_name }}:9040/"
proxypass_supervision_context: /supervision-api/
proxypass_supervision_target: "http://{{ supervision_api_name }}:9050/"
server_admin: servicecenter+allustaging@gofore.com
ssl_certificate_file: cert.pem
ssl_certificate_key_file: privkey.pem
ssl_certificate_chain_file: chain.pem
mapproxy_block_by_referer: true
